### ISSUE TITLE
deepface is just started getting exception while building conda package

### ISSUE THREAD

**Issue by serengil** [conda-forge/deepface-feedstock#7]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

As you can find in [this PR](https://github.com/conda-forge/deepface-feedstock/pull/6)'s actions, deepface is getting the following error while building its conda package. setup.py is reading dependencies from requirements.txt and this is not new thing. something has to be changed in the conda builder.

```shell
  Running command python setup.py egg_info
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "/home/conda/feedstock_root/build_artifacts/deepface_1704766023421/work/setup.py", line 6, in <module>
      with open("requirements.txt", "r", encoding="utf-8") as f:
  FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
```

### Installed packages

```shell
-
```

### Environment info

```shell
-
```

**Comment by BastianZim** [comment]
Hi @serengil, that is because the `requirements.txt` is not available in the source distribution, but it is required when building from source.

Ref:
- https://files.pythonhosted.org/packages/3f/be/b954c0f70a5eb699661cd4bbda485d68f012f80329ea7afbdf9663189b30/deepface-0.0.81.tar.gz
- https://github.com/serengil/deepface/blob/master/setup.py#L6

0.0.80 also had this error, but the PR was merged despite the checks failing, which should not have been done. 
Ref: https://github.com/conda-forge/deepface-feedstock/pull/5

The last time it worked was in 0.079 because there the requirements were specified in the setup.py and not in a separate file.
Ref: https://files.pythonhosted.org/packages/14/40/89554f19133bdab441b1baabf0c4942b022277f4470a0df501eadbd93570/deepface-0.0.79.tar.gz

To fix the PR now, we can manually include the missing files, but it would be good for them to be included in the source distribution so that the package can be built with all of the required files.

**Comment by BastianZim** [comment]
OK, I tried it a bit, but we would have to manually copy the file in which makes it a bit difficult. Ideally, you could cut a new release with the files included and then it should work here as well.

**Comment by serengil** [comment]
for the new release, should I have to copy the requirements.txt manually or I should not do anything until a dependency changed?

**Comment by BastianZim** [comment]
They just need to be included in the setup.py file. 

This PR should fix it: https://github.com/serengil/deepface/pull/950

**Comment by serengil** [comment]
Hey @BastianZim again, deepface's new version is getting error in the [latest PR](https://github.com/conda-forge/deepface-feedstock/pull/13). Interestingly, that error appears not for all checks. Do you have any idea why this happens?

Same issue happens in retinaface's latest PR as well - https://github.com/conda-forge/retina-face-feedstock/pull/4

```
    import cv2
ImportError: libEGL.so.1: cannot open shared object file: No such file or directory
WARNING: Tests failed for deepface-0.0.87-py39hf3d152e_0.conda - moving package to /home/conda/feedstock_root/build_artifacts/broken
```

**Comment by BastianZim** [comment]
Hmm that might be related to https://conda-forge.org/docs/maintainer/knowledge_base/#core-dependency-tree-packages-cdts. Let me check.
